polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^$',views.hola, name='home'),
    # url(r'^POS/$',views.hola, name='home'),
    url(r'^consultaLista/$',views.simple_upload, name='consultaLista'),
    url(r'^consultaUnica/$',views.get_name, name='consultaUnica'),
    url(r'^masInformacion/$',views.masInformacion, name='masInformacion'),
    url(r'^descarga/$',views.descargaExcel, name='descarga'),
    # url(r'^hola/$',views.hola,name='hola'),
    # url(r'^elMejorBoton/',views.elMejorBoton),
]

posAPP/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^', include('polls.urls')),
    url(r'^pos/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/forms.py
from django import forms
from django.forms import ModelForm, CharField, TextInput
class NameForm(forms.Form):
    your_name = forms.CharField(label='',min_length=5, max_length=8,widget=TextInput(attrs={'class':'form-control','pattern':'[0-9]+','min_value':'1000' ,'title':'Ingrese solo numeros.'}))
# 	your_name = forms.CharField(label='',min_length=5, max_length=8, widget=TextInput(attrs={'class':'form-control','autocomplete': 'off','pattern':'[0-9]+', 'title':'Ingrese solo numeros.'}))
class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

templates/ConsultaLista.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    {% load static %}
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{%static 'polls/css/personal.css'%}">
    <title>POS!</title>
        <img src="{% static 'headerpos.jpg' %}" class="img-fluid rounded mx-auto d-block" alt="Responsive image">
  </head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <style type="text/css">
#id_your_name{
  width: 500px;
}
.loader {
    position: fixed;
    left: 0px;
    top: 0px;
    width: 100%;
    height: 100%;
    z-index: 9999;
    background: url("{% static 'gifloader.gif' %}") 50% 50% no-repeat rgb(249,249,249);
    opacity: .8;
}

.custom-file-input:lang(en)~.custom-file-label::after {
    content: "Buscar";
}

.custom-file-input:lang(en)~.custom-file-label::after {
    content: "Buscar";
}

    </style>
  <body class="p-3 mb-2 text-blue">

    <div class="jumbotron style="background-color:#00F3FF"">
    <p class="text-center" style="font-size: 20px;"> Suba un archivo Excel con un listado de documentos
</p>

{% block content %}
<form method="post" enctype="multipart/form-data" onsubmit="showHide();">
<div class="row align-items-center justify-content-center">
{% csrf_token %}
<!--    <button type="button" class="btn btn-primary"> 
        <input class="btn btn-primary" type="file" name="myfile" accept=".xlsx" value="subir archivo">

    </button>-->
   <div class="custom-file" style="width: 30%;">
    <input type="file" name="myfile" accept=".xlsx" class="custom-file-input" id="validatedCustomFile" required>
    <label class="custom-file-label" for="validatedCustomFile">Seleccionar archivo</label>
  </div>
</div>
    <div id="archivoSubido" class="row align-items-center justify-content-center" style="margin-top:20px; display: none;">
        <button type="submit" style="width: 195px;">Procesar archivo</button>
    </div>
            {% if error != False %}
        <p class="text-center" style="color: red;
                                      font-size: 1,6em;">
        ERROR: {{error}}
                                      </p>
        {% endif %}
    </form>
          {% if uploaded_file_url %}
            <a href="media/{{ archivoDescarga }}">download</a>
          {% endif %}
          {% endblock %}     

</div>
 <div class="loader" id="hidden_div" style="display:none">
        <div class="text-center">
        </div>
        
      </div>
    <div  class="text-right">
  <a href="{% url 'home' %}" class="btn btn-outline-info" >Volver</a>
</div>
</body>
  <!-- <tbody>
    <tr>
      
      {% for i in listaPuco1_ %}
      <th scope="col">{{i}}</th>
      {% endfor %}
    </tr>
    <tr>
      <th scope="row">2</th>
       {% for i in listaPuco2_ %}
      <td>{{i}}</td>
      {% endfor %}
    </tr>
    <tr>
      <th scope="row">3</th>
       {% for i in listaPuco3_ %}
      <td>{{i}}</td>
      {% endfor %}
    </tr>
  </tbody> -->
  <footer>

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content --> 
        <div class="text-center">
        <h5 class="text-uppercase">Municipalidad de San Miguel</h5>
       
                  <p>Paginas a las que consulta esta aplicacion:</p>
        <p><strong>PUCO</strong></p>
        <p><strong>Superintendencia de salud</strong> </p>
        <p><strong>IOMA</strong></p>
        <p><strong>Plan sumar</strong> </p>
        <p><strong>PAMI</strong></p>

        </div>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-6 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Contactos:</h5>

        
          <div class="text-center">
            <ul class="list-unstyled">
             <li>
            <a href="http://www.msm.gov.ar/">MSM</a>
          </li>
          <li>
            <a href="http://www.intranet.msm.gov.ar/">Intranet</a>
          </li>
          <li>
            <a href="https://twitter.com/munisanmiguelok?lang=es">Twitter MSM</a>
          </li>
          <li>
            <a href="https://twitter.com/smconectado?lang=es">SM conectado</a>
          </li>
        </ul>
          </div>
         

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2018 Desarrollado por la Municipalidad de San Miguel.
    <a href="https://mdbootstrap.com/bootstrap-tutorial/"> http://www.msm.gov.ar/</a>
  </div>
  <!-- Copyright -->

</footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript">
$(window).load(function() {
    $(".loader");
});
</script>

<script type="text/javascript">
$('input[type=file]').change(function(){
    $("#archivoSubido").show();

});
</script>
<script type="text/javascript">
 function showHide() {
   var div = document.getElementById("hidden_div");
   if (div.style.display == 'none') {
     div.style.display = '';
   }
   else {
     div.style.display = 'none';
   }
 }
</script>
  </body>
</html>

templates/ConsultaListaDescargaCompleta.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    {% load static %}
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{%static 'polls/css/personal.css'%}">
    <title>POS!</title>
    <img src="{% static 'headerpos.jpg' %}" class="img-fluid rounded mx-auto d-block" alt="Responsive image">
  </head>
  <style type="text/css">
#id_your_name{
  width: 500px;
}
.loader {
    position: fixed;
    left: 0px;
    top: 0px;
    width: 100%;
    height: 100%;
    z-index: 9999;
    background: url("{% static 'gifloader.gif' %}") 50% 50% no-repeat rgb(249,249,249);
    opacity: .8;
}
    </style>
  <body class="p-3 mb-2 text-blue">

    <div class="jumbotron style="background-color:#00F3FF"">
      <p class="text-center" style="font-size: 20px;">
        Presione para descargar el archivo excel.
      </p>

{% block content %}

    <div class="row align-items-center justify-content-center" style="margin-top:20px;">
         
         <a href="{% url 'descarga' %}"> <button style="width: 195px;">Descargar archivo</button> </a>
    </div>
   <!--  <form action="" method="POST">
    <button type="submit" value="Click" style="width: 195px;">Descargar archivo</button>
  </form> -->
 {% endblock %}     

</div>
 <div class="loader" id="hidden_div" style="display:none">
        <div class="text-center">
        </div>
        
      </div>
        <div  class="text-right">
  <a href="{% url 'consultaLista' %}" class="btn btn-outline-info" >Volver</a>
</div>
</body>
  <!-- <tbody>
    <tr>
      
      {% for i in listaPuco1_ %}
      <th scope="col">{{i}}</th>
      {% endfor %}
    </tr>
    <tr>
      <th scope="row">2</th>
       {% for i in listaPuco2_ %}
      <td>{{i}}</td>
      {% endfor %}
    </tr>
    <tr>
      <th scope="row">3</th>
       {% for i in listaPuco3_ %}
      <td>{{i}}</td>
      {% endfor %}
    </tr>
  </tbody> -->

  <footer>

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content --> 
        <div class="text-center">
        <h5 class="text-uppercase">Municipalidad de San Miguel</h5>
       
                  <p>Paginas a las que consulta esta aplicacion:</p>
        <p><strong>PUCO</strong></p>
        <p><strong>Superintendencia de salud</strong> </p>
        <p><strong>IOMA</strong></p>
        <p><strong>Plan sumar</strong> </p>
        <p><strong>PAMI</strong></p>

        </div>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-6 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Contactos:</h5>

        <ul class="list-unstyled">
          <li>
            <a href="http://www.msm.gov.ar/">MSM</a>
          </li>
          <li>
            <a href="http://www.intranet.msm.gov.ar/">Intranet</a>
          </li>
          <li>
            <a href="https://twitter.com/munisanmiguelok?lang=es">Twitter MSM</a>
          </li>
          <li>
            <a href="https://twitter.com/smconectado?lang=es">SM conectado</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2018 Desarrollado por la Municipalidad de San Miguel.
    <a href="https://mdbootstrap.com/bootstrap-tutorial/"> http://www.msm.gov.ar/</a>
  </div>
  <!-- Copyright -->

</footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript">
$(window).load(function() {
    $(".loader");
});
</script>
<script type="text/javascript">
 function showHide() {
   var div = document.getElementById("hidden_div");
   if (div.style.display == 'none') {
     div.style.display = '';
   }
   else {
     div.style.display = 'none';
   }
 }
</script>
  </body>
</html>

templates/ConsultaUnica.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <div id="container">
    <img src="{% static 'headerpos.jpg' %}" class="img-fluid rounded mx-auto d-block" alt="Responsive image">
</div>
  <div class="header">
</div>
<section class="content">
</section>
    <!-- Required meta tags -->
    
<style type="text/css">
#id_your_name{
  width: 500px;
}
.loader {
    position: fixed;
    left: 0px;
    top: 0px;
    width: 100%;
    height: 100%;
    z-index: 9999;
    background: url("{% static 'gifloader.gif' %}") 50% 50% no-repeat rgb(249,249,249);
    opacity: .8;
}
    </style>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap.css' %}">    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <title>POS.</title>
</head>
    <body class="p-3 mb-2">
	<div class="jumbotron">
<!--     <div class="col md-1">
     <span class="ingrese">ingrese el documento:</span>  
    </div>
    <div class="col md-1">
     {% csrf_token %}
     {{ form }}
    </div>
    <div class="col md-3"> 
     <input type="submit" class="btn btn-info" value="Aceptar">
    </div>
</form> -->
<div  class="text-right">
  <a href="{% url 'home' %}" class="btn btn-outline-info" >Volver</a>
</div>
<div class="row align-items-center justify-content-center">


<form method="post" name="installer" onsubmit="showHide();">
{% csrf_token %}
  	<div class="input-group">
  	<span class="input-group-text" id="">INGRESE EL DOCUMENTO</span>


     <input type="text" name="your_name" minlength="5" required="" title="Ingrese solo numeros." id="id_your_name" pattern="[0-9]+" min_value="1000" class="form-control" maxlength="8" autocomplete="off">

      <input type="submit" class="btn btn-info" value="Buscar" name="submit" style="background-color: #00b2e9; border-color: #00b2e9;">

      <div class="loader" id="hidden_div" style="display:none">

      	<div class="text-center">
      	</div>
      	
      </div>
 </div>
  </form>
</div>
</div>


<!--    <div class="d-flex justify-content-center">
     <div class="input-group-prepend">
   {% csrf_token %}
        <span class="input-group-text" id="">INGRESE DOCUMENTO</span>
        {{ form }}
        <input type="submit" class="btn btn-info" value="Aceptar">
        </div>
   </div>
    -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>

<script type="text/javascript">
$(window).load(function() {
    $(".loader");
});
</script>
<script type="text/javascript">
 function showHide() {
   var div = document.getElementById("hidden_div");
   if (div.style.display == 'none') {
     div.style.display = '';
   }
   else {
     div.style.display = 'none';
   }
 }
</script>
  </body>
</html>

templates/IndexPOS.html
<!DOCTYPE html>
<html>
<head>


  <title> POS</title>
{% load static %}
<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

<link rel="stylesheet" type="text/css" href="{% static '/polls/css/bootstrap.css' %}">
<link rel="stylesheet" type="text/css" href="{% static '/polls/css/styleshome.css' %}">
<link rel="stylesheet" href="{% static '/polls/css/bootstrap.min2.css' %}" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
</head>
<div class = "banner">
   <div class="imagen">
   	 <img src="{% static 'headerpos.jpg' %}" class="img-fluid rounded mx-auto d-block" alt="Responsive image">
   </div>
</div>
<body>
  <div class="row">
    <div class="col-md-12 text-center">
      <h2 class="mrng-30-top">Elija una de las opciones</h2>
    </div>
  </div>
  
  <div class="row">
  		<div class="col-md-2 col-sm-0 col-xs-6"> </div>
  	    <div class="col-md-4 col-sm-6 col-xs-3"> <a href="{% url 'consultaUnica' %}" class="btn btn-sm animated-button thar-one">Consulta unica</a> </div>
   		<div class="col-md-4 col-sm-6 col-xs-3"> <a href="{% url 'consultaLista' %}" class="btn btn-sm animated-button thar-two">Consulta masiva</a> </div>
		<div class="col-md-2 col-sm-0 col-xs-6"> </div>
  </div>
  <footer class="jumbotron text-center">
  </footer>
</body>
<script src="{% static 'polls/js/jquery-3.3.1.slim.min.js' %}" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

<script src="{% static 'popper.min.js' %}" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>

<script src="{% static 'polls/js/bootstrap.min.js' %}" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

</html>

templates/MasInfo.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <!-- Required meta tags -->
    {% load static %}
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
        <link rel="shortcut icon" type="image/png" href="{& static 'favicon.ico' %}"/>
        <style type="text/css">
      body{
    background: linear-gradient(white,white, #70b6e7,#70b6e7);
  background-repeat: repeat;
  background-size: cover;
  background-position: absolute; 
      }
      head{
        background-color: white;
      }
      .jumbotron{
        opacity: 0.73;
        color: black;
      }
    </style>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>POS!</title>
        <img src="{% static 'headerpos.jpg' %}" class="img-fluid rounded mx-auto d-block" alt="Responsive image">
  </head>
  <body class="p-3 mb-2 text-blue">

    <div class="jumbotron style="background-color:#00F3FF"">
<!-- DENTRO DEL JUMBOTRON -->
<div class="text-center">
  <strong> DATOS PROGRAMA SUMAR</strong>
<p> {{sumar_}}</p>
</div>

{% for elemento in listaPamis_ %}
    {% if forloop.counter|divisibleby:2 %}
       <table class="table text-center">
        <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">D.MODULO</th>
              <th scope="col">RED</th>
              <th scope="col">PRESTADOR</th>
            </tr>
        </thead>
      <tbody>
        {% for a,b,c in elemento %}
            <tr>
              <th scope="row">{{forloop.counter}}</th>
              <td>{{a}}</td>
              <td>{{b}}</td>
              <td>{{c}}</td>
            </tr>

        {% endfor %}
      </tbody>
    </table>

      
    {% else %}
            <div class="text-center">
             <strong> DATOS PAMI - {{elemento}} </strong>              
            </div>
    {% endif %}
  {% endfor %}






<!-- FUERA DEL JUMBOTRON -->
</div>

  


  <div  class="text-right">
  <a href="{% url 'consultaUnica' %}" class="btn btn-outline-info" >Volver</a>
</div>
  <footer class="page-footer font-small blue pt-4 mt-4">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content --> 
        <div class="text-center">
        <h5 class="text-uppercase">MUNICIPALIDAD DE SAN MIGUEL</h5>

                  <span>PAGINAS EN LAS QUE CONSULTA ESTA APLICACION:</span>
        <p><strong>PUCO</strong></p>
        <p><strong>SUPERINTENDENCIA DE SALUD</strong> </p>
        <p><strong>IOMA</strong></p>
        <p><strong>PLAN SUMAR</strong> </p>
        <p><strong>PAMI</strong></p>

        </div>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-6 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Contactos:</h5>

        <ul class="list-unstyled">
          <li>
            <a href="http://www.msm.gov.ar/">MSM</a>
          </li>
          <li>
            <a href="http://www.intranet.msm.gov.ar/">Intranet</a>
          </li>
          <li>
            <a href="https://twitter.com/munisanmiguelok?lang=es">Twitter MSM</a>
          </li>
          <li>
            <a href="https://twitter.com/smconectado?lang=es">SM conectado</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2018 Desarrollado por la Municipalidad de San Miguel.
    <a href="https://mdbootstrap.com/bootstrap-tutorial/"> http://www.msm.gov.ar/</a>
  </div>
  <!-- Copyright -->

</footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>